name: glow-docs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - nptyping=1.3.0
  - numpy>=1.17.4
  - pandas>=0.25.3
  - pip
  - scikit-learn=0.22.1
  - typeguard=2.9.1
  - pip:
      - hail>=0.2.58
      - sphinx>=3.0.0
      - sphinx_rtd_theme
      - sphinx-autobuild
      - sphinx-prompt
      - Sphinx-Substitution-Extensions==2020.05.23.0
      - sphinx-tabs # Code tabs (Python/Scala)
